name: task_manager_app
description: Task Manager App — Flutter CRUD with Back4App BaaS (CPAD Assignment)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Back4App / Parse SDK
  parse_server_sdk_flutter: ^10.7.0

  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.0

  # State Management
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
